### ISSUE TITLE
evaluateJSAsync Hangs

### ISSUE THREAD

**Issue by ebebbington** [saucelabs/foxdriver#24]
Hello, this is maybe leaning more towards a question than an issue, so if you have a discord channel or similar, im happy to discuss there, but i can't seem to get `evaluateJSAsync` to work :/

```js
//
// This block was taken from your README, but only the lines to get logs were moddified, to instead evaluate
//

import Foxdriver from 'foxdriver'

(async () => {
  const { browser, tab } = await Foxdriver.launch({
    url: 'https://www.mozilla.org/en-US'
  });

  // enable actor
  await tab.console.startListeners();
  // wait until page is loaded
  await new Promise((resolve) => setTimeout(resolve, 3000));
  // evaluate
  const result = await tab.console.evaluateJSAsync(`return document.title`); // also tried just `document.title`
  console.log(result);

  // close browser
  browser.close();
})()
```

But this just hangs. All i'm hoping to do is just evaluate expressions

**Comment by ebebbington** [comment]
Also hang when doing `const result = await tab.console.evaluateJSAsync((a, b, c) => a + b + c, 1, 2, 3);` (taken from your test files)

**Comment by benmalka** [comment]
@ebebbington
try attaching the tab using `await tab.attach()`

**Comment by ebebbington** [comment]
Yeah that does the trick, thanks @benmalka :) It would be useful if some docs could be added around this? 

I'll leave this issue open so you decide its fate :P
